# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y libcurl4-openssl-dev uuid-dev
    v1/tools/build.sh --run-unittests
  displayName: Run the build
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: current
    downloadType: specific
    itemPattern: v1/deps/c-utility/build/*.txt
    downloadPath: $(System.ArtifactsDirectory)
