# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    sudo apt-get update
    apt-cache madison libssl-dev
  displayName: List available package versions for libssl-dev
- script: |
    set -x
    sudo apt-get update
    libssl_version=$(apt-cache madison libssl-dev | grep -e "libssl-dev | 1.0" | head -1 | awk '{print $3}')
    sudo apt-get install -y libcurl4-openssl-dev uuid-dev libssl-dev=$libssl_version
  displayName: Install prerequisites
- script: apt list --installed
  displayName: list installed packages
- script: v1/tools/build.sh --run-unittests
  displayName: Run the build
- task: CopyFiles@2
  displayName: Collect build logs
  condition: always()
  inputs:
    SourceFolder: v1/deps/c-utility/build
    Contents: '*.txt'
    TargetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  displayName: Publish build logs
  condition: always()
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: build logs
    Parallel: true
    ParallelCount: 8